export const ZONES = [
  {
    id: 'childhood',
    name: 'Childhood',
    subtitle: 'The Beginning',
    period: '',
    description: 'A curious kid with big dreams',
    colors: { primary: 0xfca5a5, secondary: 0xf87171, accent: 0xfecaca },
    position: { x: -20, z: 14 },
    dialogue: [
      { speaker: 'narrator', text: 'Every great journey starts small...' },
      { speaker: 'jonathan', text: 'Hi! I\'m Jonathan. When I was a kid, I was always curious about how things worked.' },
      { speaker: 'jonathan', text: 'I loved taking apart gadgets, playing video games, and wondering — how do they make these?' },
      { speaker: 'narrator', text: 'That curiosity would lead him down an incredible path. Let\'s follow along...' },
    ],
    collectibles: [],
    sideQuests: [],
  },
  {
    id: 'binus',
    name: 'BINUS',
    subtitle: 'Campus',
    period: '2018-2022',
    description: 'Bachelor of Computer Science',
    colors: { primary: 0x4ade80, secondary: 0x22c55e, accent: 0x86efac },
    position: { x: 0, z: 0 },
    dialogue: [
      { speaker: 'narrator', text: 'Our story begins at BINUS University...' },
      { speaker: 'jonathan', text: '3 and a half years of computer science — algorithms, data structures, software engineering.' },
      { speaker: 'jonathan', text: 'Graduated with a GPA of 3.63 and published a research paper on autonomous drone navigation with IEEE.' },
      { speaker: 'narrator', text: 'A solid foundation. The next chapter awaited...' },
    ],
    collectibles: [
      { id: 'binus-1', label: 'Bachelor of Computer Science, GPA 3.63' },
      { id: 'binus-2', label: 'Published IEEE paper on Autonomous Drone Indoor Navigation' },
      { id: 'binus-3', label: 'Built foundation in computer science fundamentals' },
    ],
    sideQuests: [
      {
        id: 'binus-thesis',
        name: 'Drone Thesis',
        emoji: '🛸',
        color: 0x34d399,
        offset: { x: 10, z: 12 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The Drone Project' },
          { speaker: 'jonathan', text: 'For my thesis, I built a drone pathfinding system using 3D mapping inside Unity.' },
          { speaker: 'jonathan', text: 'Unity generated the navigation path, then sent real flight commands to a physical drone.' },
          { speaker: 'jonathan', text: 'The drone reported its location back using its onboard gyroscope. Real hardware, real software, real-time.' },
          { speaker: 'narrator', text: 'Published as an IEEE paper: ieeexplore.ieee.org/document/9915133' },
        ],
        link: 'https://ieeexplore.ieee.org/document/9915133',
      },
    ],
  },
  {
    id: 'bca',
    name: 'BCA',
    subtitle: 'Code Lab',
    period: '2021-2022',
    description: 'Software Quality Assurance Intern',
    colors: { primary: 0x60a5fa, secondary: 0x3b82f6, accent: 0x1e293b },
    position: { x: 20, z: -14 },
    dialogue: [
      { speaker: 'narrator', text: 'While still in university, Jonathan landed his first real tech role...' },
      { speaker: 'jonathan', text: 'Bank Central Asia — one of the biggest banks in Indonesia. I was testing APIs that handled real money.' },
      { speaker: 'jonathan', text: 'Postman, SoapUI, JMeter became my daily tools. I even built automation scripts to test API migrations.' },
      { speaker: 'narrator', text: 'Pure programming. Pure problem-solving. The foundation was being built.' },
    ],
    collectibles: [
      { id: 'bca-1', label: 'Manual & automated testing of banking APIs (Postman, SoapUI, JMeter)' },
      { id: 'bca-2', label: 'Built automation tools for API migration testing' },
      { id: 'bca-3', label: 'Tested transactional banking system APIs across versions' },
    ],
    sideQuests: [],
  },
  {
    id: 'ey',
    name: 'EY',
    subtitle: "Explorer's Guild",
    period: '2022-2024',
    description: 'Associate Consultant',
    colors: { primary: 0xfbbf24, secondary: 0xf59e0b, accent: 0xfde68a },
    position: { x: 40, z: -28 },
    dialogue: [
      { speaker: 'narrator', text: 'The adventure expanded. Ernst & Young — the global consulting firm.' },
      { speaker: 'jonathan', text: 'Every few months, a new client, a new industry, a new challenge. Health insurance, banking, government.' },
      { speaker: 'jonathan', text: 'I helped migrate an entire insurance company to Azure Cloud. Wrote a 5-year IT strategy for a state bank.' },
      { speaker: 'jonathan', text: 'Even worked on separating an Australian bank\'s technology during an M&A deal. Wild times.' },
      { speaker: 'narrator', text: 'From code to clients — Jonathan was becoming more than just a developer.' },
    ],
    collectibles: [
      { id: 'ey-1', label: 'Cloud Migration to Azure Data Cloud for health insurance company' },
      { id: 'ey-2', label: 'Data Center capacity planning strategy for state-owned bank' },
      { id: 'ey-3', label: '5-Year IT Strategic Plan with capability gap assessments' },
      { id: 'ey-4', label: 'Bank Separation PMO for technology & data workstream' },
    ],
    sideQuests: [
      {
        id: 'ey-proposals',
        name: 'Proposals',
        emoji: '📝',
        color: 0xf59e0b,
        offset: { x: -10, z: -12 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The Proposal Machine' },
          { speaker: 'jonathan', text: 'At EY, I didn\'t just execute — I also wrote proposals to win new projects.' },
          { speaker: 'jonathan', text: 'Scoping client needs, estimating effort, presenting solutions. It taught me to think like a business.' },
        ],
      },
      {
        id: 'ey-datamodeling',
        name: 'Data Modeling',
        emoji: '🗄️',
        color: 0xfbbf24,
        offset: { x: 3, z: -14 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The Data Architect' },
          { speaker: 'jonathan', text: 'For the cloud migration project, I did hands-on data modeling and wrote testing scripts.' },
          { speaker: 'jonathan', text: 'Validating data integrity across legacy and Azure environments. Every row had to match.' },
        ],
      },
      {
        id: 'ey-strategy',
        name: 'IT Strategy',
        emoji: '🗺️',
        color: 0xd97706,
        offset: { x: -3, z: 14 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The Strategist' },
          { speaker: 'jonathan', text: 'I helped build a 5-year IT roadmap for a state-owned bank. Capability gaps, restructuring plans, upskilling roadmaps.' },
          { speaker: 'jonathan', text: 'Seeing technology from a 30,000-foot view completely changed how I think about systems.' },
        ],
      },
      {
        id: 'ey-separation',
        name: 'Bank Separation',
        emoji: '🏦',
        color: 0xeab308,
        offset: { x: 10, z: -12 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The Great Divide' },
          { speaker: 'jonathan', text: 'An Australian multinational bank was splitting off its Indonesian operations. M&A-driven tech separation.' },
          { speaker: 'jonathan', text: 'I was the BA and PMO for the technology and data workstream. Coordinating between two entities, two countries.' },
        ],
      },
    ],
  },
  {
    id: 'blibli',
    name: 'Blibli',
    subtitle: 'Audit Fortress',
    period: '2024-2025',
    description: 'Senior IT Internal Audit Officer',
    colors: { primary: 0xa78bfa, secondary: 0x8b5cf6, accent: 0x7c3aed },
    position: { x: 60, z: -42 },
    dialogue: [
      { speaker: 'narrator', text: 'Next stop: Blibli — one of Indonesia\'s largest e-commerce platforms.' },
      { speaker: 'jonathan', text: 'I switched sides. Instead of building systems, I was now auditing them.' },
      { speaker: 'jonathan', text: 'Data governance against Indonesia\'s new privacy law. Cybersecurity audits benchmarked to NIST and ISO.' },
      { speaker: 'jonathan', text: 'It gave me a completely different perspective — seeing systems from the defender\'s point of view.' },
      { speaker: 'narrator', text: 'The auditor\'s eye would prove invaluable for what came next...' },
    ],
    collectibles: [
      { id: 'blibli-1', label: 'Data Governance Assessment against UU PDP regulations' },
      { id: 'blibli-2', label: 'End-to-end cybersecurity audit benchmarked to NIST/ISO' },
      { id: 'blibli-3', label: 'Application integrity reviews for system reliability' },
    ],
    sideQuests: [
      {
        id: 'blibli-automation',
        name: 'Audit Automation',
        emoji: '🤖',
        color: 0x8b5cf6,
        offset: { x: -3, z: 14 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The Automation Pioneer' },
          { speaker: 'jonathan', text: 'Manual auditing was slow. So I built automation programs to speed up the audit process.' },
          { speaker: 'jonathan', text: 'Scripts that could pull data, cross-reference controls, and flag issues automatically.' },
          { speaker: 'narrator', text: 'The auditor who codes — a rare and powerful combination.' },
        ],
      },
      {
        id: 'blibli-ai',
        name: 'AI Adoption',
        emoji: '🧠',
        color: 0xa78bfa,
        offset: { x: 3, z: 14 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The AI Evangelist' },
          { speaker: 'jonathan', text: 'I introduced the audit team to AI tools. Showed them how to use LLMs for analysis, summarization, and research.' },
          { speaker: 'jonathan', text: 'It wasn\'t just about the tools — it was about changing how the team thinks about efficiency.' },
        ],
      },
    ],
  },
  {
    id: 'gspe',
    name: 'GSPE',
    subtitle: 'Command Center',
    period: '2025-Present',
    description: 'Technical Lead',
    colors: { primary: 0xf472b6, secondary: 0xec4899, accent: 0xf9a8d4 },
    position: { x: 80, z: -56 },
    dialogue: [
      { speaker: 'narrator', text: 'The final chapter (so far). GSPE — where everything came together.' },
      { speaker: 'jonathan', text: 'Technical Lead. 19 enterprise systems. 9 departments. 505+ tracked requests. This is the big picture.' },
      { speaker: 'jonathan', text: 'I modernized the entire ERP stack — Docker, .NET, Vue.js, PostgreSQL. Built about 10 AI prototypes.' },
      { speaker: 'jonathan', text: 'RAG systems, computer vision, digital twins... and an IoT product called NexaBrick, from hardware to sales.' },
      { speaker: 'jonathan', text: 'Now every developer on my team has an AI coding agent. Plan-Approve-Execute. The future is here.' },
      { speaker: 'narrator', text: 'From student to tech lead. The journey continues...' },
    ],
    collectibles: [
      { id: 'gspe-1', label: 'Request Management System: 505+ tickets across 19 systems, 9 departments' },
      { id: 'gspe-2', label: 'ERP Modernization: Docker, .NET, Vue.js, PostgreSQL' },
      { id: 'gspe-3', label: '~10 AI prototypes: RAG, computer vision, digital twin, tender processor' },
      { id: 'gspe-4', label: 'NexaBrick IoT ecosystem: hardware to commercial execution' },
    ],
    sideQuests: [
      {
        id: 'gspe-iot',
        name: 'Smart Factory',
        emoji: '🏭',
        color: 0x4ade80,
        offset: { x: -14, z: 0 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The Smart Factory & IoT Data Center' },
          { speaker: 'jonathan', text: 'First, we built a containerized mini data center — a physical server rack with containment, packed with IoT sensors monitoring temperature, humidity, power, and airflow.' },
          { speaker: 'jonathan', text: 'Then we scaled up to a smart factory: monitoring water treatment systems, power feeds for CNC machines, and smart meeting rooms.' },
          { speaker: 'jonathan', text: 'We used OpenCV for activity detection in the production area — tracking movement patterns and safety compliance in real-time.' },
          { speaker: 'narrator', text: 'From a containerized rack to a living, breathing smart factory.' },
        ],
      },
      {
        id: 'gspe-nexabrick',
        name: 'NexaBrick',
        emoji: '📦',
        color: 0xf472b6,
        offset: { x: 0, z: 16 },
        link: 'https://www.ioteknologi.com/',
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: From Prototype to Product' },
          { speaker: 'jonathan', text: 'NexaBrick started as an IoT experiment and became a full commercial product.' },
          { speaker: 'jonathan', text: 'I handled everything end-to-end: hardware engineering, software, pricing strategy, sales deck, product catalogue.' },
          { speaker: 'jonathan', text: 'It\'s one thing to write code. It\'s another to ship a physical product to market.' },
          { speaker: 'narrator', text: 'Check it out: ioteknologi.com' },
        ],
      },
      {
        id: 'gspe-ai',
        name: 'AI R&D Lab',
        emoji: '🔬',
        color: 0x60a5fa,
        offset: { x: 14, z: 0 },
        dialogue: [
          { speaker: 'narrator', text: 'Side Quest: The AI Laboratory' },
          { speaker: 'jonathan', text: 'I set up an R&D pipeline to evaluate open-source AI tools. About 10 prototypes delivered.' },
          { speaker: 'jonathan', text: 'RAG systems for document search. Computer vision for object detection. Digital twins of the production line.' },
          { speaker: 'jonathan', text: 'And an AI tender processor that reads 100-page documents and extracts requirements automatically.' },
        ],
      },
    ],
  },
  {
    id: 'future',
    name: 'What\'s Next?',
    subtitle: 'The Future',
    period: '',
    description: 'The journey continues...',
    colors: { primary: 0x38bdf8, secondary: 0x0ea5e9, accent: 0x7dd3fc },
    position: { x: 100, z: -70 },
    dialogue: [
      { speaker: 'narrator', text: 'The story isn\'t over. In fact, it\'s just getting started.' },
      { speaker: 'jonathan', text: 'I\'m always looking for the next challenge. Whether it\'s leading teams, building AI systems, or creating products.' },
      { speaker: 'jonathan', text: 'If my journey resonates with you, let\'s connect. I\'d love to hear from you.' },
      { speaker: 'narrator', text: 'Thanks for exploring Jonathan\'s journey. Reach out below!' },
    ],
    collectibles: [],
    sideQuests: [],
    isContactZone: true,
  },
];

export const SKILLS = [
  {
    group: 'Leadership & Strategy',
    color: 0xfbbf24,
    items: [
      { name: 'Project Management', level: 0.9 },
      { name: 'Strategic Planning', level: 0.85 },
      { name: 'Business Analysis', level: 0.8 },
      { name: 'Process Improvement', level: 0.85 },
    ],
  },
  {
    group: 'Governance & Compliance',
    color: 0xa78bfa,
    items: [
      { name: 'IT Audit', level: 0.9 },
      { name: 'Risk Assessment', level: 0.85 },
      { name: 'Data Governance', level: 0.8 },
      { name: 'Cybersecurity', level: 0.75 },
    ],
  },
  {
    group: 'Engineering',
    color: 0x60a5fa,
    items: [
      { name: 'Programming', level: 0.8 },
      { name: 'Data Analysis', level: 0.8 },
      { name: 'Data Modeling', level: 0.75 },
      { name: 'IoT / Hardware', level: 0.7 },
    ],
  },
  {
    group: 'Innovation',
    color: 0xf472b6,
    items: [
      { name: 'AI / ML Prototyping', level: 0.75 },
      { name: 'Computer Vision', level: 0.7 },
      { name: 'Automation', level: 0.85 },
      { name: 'Product Development', level: 0.75 },
    ],
  },
];

export const CERTIFICATIONS = [
  'IELTS Band 8',
  'AI Bronze (EY)',
  'Strategy Bronze (EY)',
  'Digital Bronze (EY)',
  'Data Warehouse (Snowflake)',
  'Data Analytics (Google)',
  'AI Foundations (IBM)',
];

export const PLAYER_CARD = {
  name: 'Jonathan Putra',
  title: 'Technology Generalist',
  subtitle: 'Advisory | Assurance | Engineering',
  location: 'Jakarta, Indonesia',
  email: 'jonathanputra23@gmail.com',
  linkedin: 'linkedin.com/in/jonathan-putra/',
};

export const TOTAL_COLLECTIBLES = ZONES.reduce((sum, z) => sum + z.collectibles.length, 0);
